# Generated by Django 4.2.27 on 2026-02-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cantact',
            new_name='Contact',
        ),
    ]
