# Generated by Django 4.2.27 on 2026-02-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_cantact_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date']},
        ),
    ]
